apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    io.kompose.service: sc-task
  name: sc-task
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: sc-task
status:
  loadBalancer: {}
